#!/usr/bin/env bash
# panel-color.sh — Set GNOME panel color from wallpaper average
# Dependencies: imagemagick (magick), python3
# Usage: ./panel-color.sh [--top] [--opacity 0.4] [--dark 15] [--apply] [--theme NAME]

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────
SAMPLE_TOP=false
OPACITY=0.85
DARKEN=15
THEME_NAME="WallpaperPanel"
APPLY=false

# ── Colors / formatting ───────────────────────────────────────────────────────
BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
RESET='\033[0m'

log()  { printf "  ${DIM}·${RESET}  %-18s ${CYAN}%s${RESET}\n" "$1" "$2"; }
ok()   { printf "  ${GREEN}✓${RESET}  %s\n" "$1"; }
err()  { printf "  ${RED}✗${RESET}  %s\n" "$1" >&2; }
warn() { printf "  ${YELLOW}!${RESET}  %s\n" "$1"; }
sep()  { printf "${DIM}%s${RESET}\n" "  ────────────────────────────────────"; }

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --top)        SAMPLE_TOP=true ;;
    --opacity)    OPACITY="$2"; shift ;;
    --dark)       DARKEN="$2"; shift ;;
    --apply)      APPLY=true ;;
    --theme)      THEME_NAME="$2"; shift ;;
    -h|--help)
      echo "Usage: $0 [--top] [--opacity 0.0-1.0] [--dark 0-100] [--apply] [--theme NAME]"
      echo "  --top          Sample only the top 10% of the wallpaper"
      echo "  --opacity N    Panel background opacity, default: 0.85"
      echo "  --dark N       Darken color by N percent, default: 15"
      echo "  --apply        Apply theme via gsettings after writing CSS"
      echo "  --theme NAME   Theme folder name, default: WallpaperPanel"
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
  shift
done

# ── Dependency check ──────────────────────────────────────────────────────────
if ! command -v magick &>/dev/null; then
  err "imagemagick not found"
  printf "     install: sudo dnf install imagemagick\n"
  exit 1
fi

# ── Header ────────────────────────────────────────────────────────────────────
echo ""
printf "  ${BOLD}panel-color${RESET}\n"
sep

# ── Get wallpaper path ────────────────────────────────────────────────────────
RAW_URI=$(gsettings get org.gnome.desktop.background picture-uri 2>/dev/null || true)
if [[ -z "$RAW_URI" || "$RAW_URI" == "''" ]]; then
  RAW_URI=$(gsettings get org.gnome.desktop.background picture-uri-dark 2>/dev/null || true)
fi

WALLPAPER_PATH=$(echo "$RAW_URI" | sed "s/'//g; s|file://||")

if [[ -z "$WALLPAPER_PATH" || ! -f "$WALLPAPER_PATH" ]]; then
  err "could not find wallpaper — set one in GNOME Settings first"
  exit 1
fi

log "wallpaper" "$(basename "$WALLPAPER_PATH")"
$SAMPLE_TOP && log "sample area" "top 10% strip" || log "sample area" "full image"
log "darken" "${DARKEN}%"
log "opacity" "$OPACITY"

sep

# ── Sample average color ──────────────────────────────────────────────────────
TMP_IMG=$(mktemp /tmp/wallpaper-sample.XXXXXX.png)
trap 'rm -f "$TMP_IMG"' EXIT

if $SAMPLE_TOP; then
  magick "$WALLPAPER_PATH" -gravity North -crop 100%x10%+0+0 +repage -resize 1x1! "$TMP_IMG"
else
  magick "$WALLPAPER_PATH" -resize 1x1! "$TMP_IMG"
fi

HEX_COLOR=$(magick "$TMP_IMG" txt:- | grep -oP '#[0-9A-Fa-f]{6}' | head -1)

if [[ -z "$HEX_COLOR" ]]; then
  err "failed to extract color from wallpaper"
  exit 1
fi

# ── Darken ────────────────────────────────────────────────────────────────────
DARKENED=$(python3 - "$HEX_COLOR" "$DARKEN" <<'PYEOF'
import sys
h = sys.argv[1].lstrip('#')
pct = int(sys.argv[2])
r, g, b = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
f = (100 - pct) / 100
print(f'#{max(0,int(r*f)):02x}{max(0,int(g*f)):02x}{max(0,int(b*f)):02x}')
PYEOF
)

RGB=$(python3 - "$DARKENED" <<'PYEOF'
import sys
h = sys.argv[1].lstrip('#')
r, g, b = int(h[0:2],16), int(h[2:4],16), int(h[4:6],16)
print(f'{r}, {g}, {b}')
PYEOF
)

FINAL_COLOR="rgba($RGB, $OPACITY)"

log "raw color" "$HEX_COLOR"
log "after darken" "$DARKENED"
log "final (rgba)" "$FINAL_COLOR"

sep

# ── Write CSS ─────────────────────────────────────────────────────────────────
THEME_DIR="$HOME/.local/share/themes/$THEME_NAME/gnome-shell"
CSS_FILE="$THEME_DIR/gnome-shell.css"
mkdir -p "$THEME_DIR"

cat > "$CSS_FILE" <<CSS
/* generated by panel-color.sh — $(date) */
/* wallpaper: $(basename "$WALLPAPER_PATH") */

#panel {
  background-color: $FINAL_COLOR;
  transition-duration: 300ms;
}

#panel .panel-button {
  color: rgba(255, 255, 255, 0.9);
}

#panel .panel-button:hover {
  background-color: rgba(255, 255, 255, 0.1);
}
CSS

ok "CSS written to $CSS_FILE"

# ── Apply ─────────────────────────────────────────────────────────────────────
if $APPLY; then
  if gsettings get org.gnome.shell.extensions.user-theme name &>/dev/null; then
    gsettings set org.gnome.shell.extensions.user-theme name "$THEME_NAME"
    ok "theme applied: $THEME_NAME"
  else
    warn "user-theme extension not active"
    printf "     set manually: GNOME Tweaks → Appearance → Shell → %s\n" "$THEME_NAME"
  fi
else
  warn "theme not applied yet"
  printf "     run with --apply, or set in GNOME Tweaks → Appearance → Shell → %s\n" "$THEME_NAME"
fi

sep
printf "  ${DIM}reload (X11): Alt+F2 → r     reload (Wayland): log out/in${RESET}\n"
echo ""
